// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: nullstring.proto

package nullstring

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// NullString ...
type NullString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Represents the actual string
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// is set to true if the string is null
	IsNotNull bool `protobuf:"varint,2,opt,name=is_not_null,json=isNotNull,proto3" json:"is_not_null,omitempty"`
}

func (x *NullString) Reset() {
	*x = NullString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nullstring_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullString) ProtoMessage() {}

func (x *NullString) ProtoReflect() protoreflect.Message {
	mi := &file_nullstring_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullString.ProtoReflect.Descriptor instead.
func (*NullString) Descriptor() ([]byte, []int) {
	return file_nullstring_proto_rawDescGZIP(), []int{0}
}

func (x *NullString) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *NullString) GetIsNotNull() bool {
	if x != nil {
		return x.IsNotNull
	}
	return false
}

var File_nullstring_proto protoreflect.FileDescriptor

var file_nullstring_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6e, 0x75, 0x6c, 0x6c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x14, 0x6e, 0x75, 0x6c, 0x6c, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x6e, 0x75,
	0x6c, 0x6c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x40, 0x0a, 0x0a, 0x4e, 0x75, 0x6c, 0x6c,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1e, 0x0a, 0x0b, 0x69, 0x73,
	0x5f, 0x6e, 0x6f, 0x74, 0x5f, 0x6e, 0x75, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x69, 0x73, 0x4e, 0x6f, 0x74, 0x4e, 0x75, 0x6c, 0x6c, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x65, 0x69, 0x77, 0x6f, 0x6c, 0x76,
	0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6e, 0x75, 0x6c, 0x6c,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x6e, 0x75, 0x6c, 0x6c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nullstring_proto_rawDescOnce sync.Once
	file_nullstring_proto_rawDescData = file_nullstring_proto_rawDesc
)

func file_nullstring_proto_rawDescGZIP() []byte {
	file_nullstring_proto_rawDescOnce.Do(func() {
		file_nullstring_proto_rawDescData = protoimpl.X.CompressGZIP(file_nullstring_proto_rawDescData)
	})
	return file_nullstring_proto_rawDescData
}

var file_nullstring_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_nullstring_proto_goTypes = []interface{}{
	(*NullString)(nil), // 0: nulltypes.nullstring.NullString
}
var file_nullstring_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nullstring_proto_init() }
func file_nullstring_proto_init() {
	if File_nullstring_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nullstring_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nullstring_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nullstring_proto_goTypes,
		DependencyIndexes: file_nullstring_proto_depIdxs,
		MessageInfos:      file_nullstring_proto_msgTypes,
	}.Build()
	File_nullstring_proto = out.File
	file_nullstring_proto_rawDesc = nil
	file_nullstring_proto_goTypes = nil
	file_nullstring_proto_depIdxs = nil
}
